name: Auto-Assign Dependabot PRs

on:
  pull_request:
    types:
      - opened

jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
      - name: Assign PR to User
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pr = context.payload.pull_request;
            if (pr.user.login === 'dependabot[bot]') {
              github.rest.issues.addAssignees({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: pr.number,
                assignees: ['FarukhSaifi']
              });
            }
